services:
  rustplusbot:
    image: ghcr.io/faithix/rustplusplus:master
    container_name: rustplusbot
    environment:
      - RPP_DISCORD_TOKEN=TOKEN
      - RPP_DISCORD_CLIENT_ID=CLIENT_ID
      - RPP_BATTLEMETRICS_TOKEN=
      - RPP_TEAM_DETECTOR_REF=feature/resilient-teamfinder-fetching
    volumes:
      - ./logs:/app/logs
      - ./instances:/app/instances
      - ./credentials:/app/credentials
      - ./maps:/app/maps
      - ./database:/app/database
    restart: unless-stopped
